core/cp/controllers/ProductsCategoriesController.php
<?php

namespace cp\controllers;

use Yii;
use common\models\products\ProductsCategories;
use common\models\products\search\ProductsCategoriesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductsCategoriesController implements the CRUD actions for ProductsCategories model.
 */
class ProductsCategoriesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ProductsCategories models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductsCategoriesSearch('drop');
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProductsCategories model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionInfo($category_id)
    {
        $searchModel = new \common\models\products\search\ProductsSearch('drop');
        $dataProvider = $searchModel->searchCategory(Yii::$app->request->queryParams);

        return $this->render('info', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }
    /**
     * Creates a new ProductsCategories model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductsCategories();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ProductsCategories model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ProductsCategories model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProductsCategories model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductsCategories the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductsCategories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

core/cp/controllers/ProductsController.php
<?php

namespace cp\controllers;

use common\helpers\myHellpers;
use common\models\MainModel;
use common\models\products\search\ProductsCategoriesSearch;
use Yii;
use common\models\products\Products;
use common\models\products\search\ProductsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductsController implements the CRUD actions for Products model.
 */
class ProductsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Products models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductsSearch('drop');
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if($model = $this->findModel($id)){
            return $this->render('view', [
                'model' => $model,
            ]);
        }else{
            $this->redirect('/');
        }
    }
    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     */
    public function actionCategories()
    {
        $searchModel = new ProductsCategoriesSearch('drop');
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('categories', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Products model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Products();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Products model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Products model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Products model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Products the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if ($model = Products::find()->where(['id'=>$id,'status_drop'=>MainModel::STATUS_PRODUCT_DROP_ACTIVE])->one()) {
            return $model;
        }
        return null;
    }
}

core/cp/views/products-categories/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\products\ProductsCategories */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="products-categories-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'alias')->textarea(['rows' => 6]) ?>

        <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

        <?= $form->field($model, 'status')->textInput() ?>

        <?= $form->field($model, 'xml_id')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'xml_parent_id')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'xml_name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'seo_keywords')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'seo_description')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'img')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'created_at')->textInput() ?>

        <?= $form->field($model, 'updated_at')->textInput() ?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

core/cp/views/products-categories/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\products\search\ProductsCategoriesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="products-categories-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'parent_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'alias') ?>

    <?= $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'status_drop') ?>

    <?php // echo $form->field($model, 'xml_id') ?>

    <?php // echo $form->field($model, 'xml_parent_id') ?>

    <?php // echo $form->field($model, 'xml_name') ?>

    <?php // echo $form->field($model, 'seo_keywords') ?>

    <?php // echo $form->field($model, 'seo_description') ?>

    <?php // echo $form->field($model, 'img') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

core/cp/views/products-categories/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\products\search\ProductsCategoriesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Drop Products Categories');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-categories-index box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'parent_id',
                'name',
                'alias:ntext',
                'content:ntext',
                // 'status',
                // 'status_drop',
                // 'xml_id',
                // 'xml_parent_id',
                // 'xml_name',
                // 'seo_keywords',
                // 'seo_description',
                // 'img',
                // 'created_at',
                // 'updated_at',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

core/cp/views/products-categories/info.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\products\search\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Drop Products');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-index box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",

            'options' => [
                'style'=>'overflow: auto; word-wrap: break-word;'
            ],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute'=>'article',

                    'label'=>'Ариткул',
                    'value' => function($model){
                        return $model->article ;
                    },

                    'contentOptions'=>['style'=>'width: 40px; '],
                    'format'=>'raw',
                ],


                [
                    'attribute' => 'name',
                    'value' => function ($model) {

                        return  Html::a($model->name, ['products/view', 'id' => $model->id]);
                    },
                    'format' => 'html',
                    'label' => 'Название продукта',
                ],

                [
                    'attribute'=>'price',
                    'value'=>function ($model, $key, $index, $widget) {
                        return $model->price .' руб.';
                    },

                    'label'=>"Рыночная цена"

                ],
                [
                    'attribute'=>'price_drop',
                    'value'=>function ($model, $key, $index, $widget) {
                        return $model->price_drop .' руб.';
                    },

                    'label'=>"Цена для партнеров "

                ],
                [
                    'attribute'=>'price_marj',
                    'value'=>function ($model, $key, $index, $widget) {
                        return ($model->price - $model->price_drop) .' руб.';
                    },

                    'label'=>"Маржинальность "

                ],
                [
                    'attribute' => 'category_id',
                    'value' => function ($model) {

                        return  Html::a($model->category->name, ['products-categories/info', 'category_id' => $model->category->id]);
                    },
                    'format' => 'html',
                    'label' => 'Категория',
                ],
               /* [
                    'attribute'=>'status',
                    'value' => function($data){
                        return \common\helpers\myHellpers::getStatusLabel($data->status, \common\models\MainModel::STATUS_SIMPLE_LIST);
                    },
                    'label'=>'Статус',
                    'format'=>'html'

                ],
                [
                    'attribute'=>'status_drop',
                    'value' => function($data){
                        return \common\helpers\myHellpers::getStatusLabel($data->status_drop, \common\models\MainModel::STATUS_SIMPLE_LIST);
                    },
                    'label'=>'Статус для Дроперов',
                    'format'=>'html'

                ],*/
                // 'price',
                // 'status',
                // 'status_drop',
                // 'xml_id',
                // 'xml_name',
                // 'xml_category',
                // 'xml_price',
                // 'xml_article',
                // 'created_at',
                // 'updated_at',
                [

                    'class' => '\kartik\grid\ActionColumn',
                    'hiddenFromExport' => true,
                    'template' => '{view}',
                    'buttons' => [

                        //view button
                        'view' => function ($url, $model) {
                            return Html::a('<span class="fa fa-search"></span> Подробнее', $url, [
                                'title' => Yii::t('app', 'View'),
                                'class'=>'btn bg-blue btn-xs  btn-flat',
                            ]);
                        },
                    ],

                    'urlCreator' => function ($action, $model, $key, $index) {
                        if ($action === 'view') {
                            $url = '/cp/products/view?id=' . $model->id;
                            return $url;
                        }
                    }
                ],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

core/cp/views/products-categories/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\products\ProductsCategories */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Drop Products Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="products-categories-view box box-primary"> 
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'parent_id',
                'name',
                'alias:ntext',
                'content:ntext',
                'status',
                'status_drop',
                'xml_id',
                'xml_parent_id',
                'xml_name',
                'seo_keywords',
                'seo_description',
                'img',
                'created_at:datetime',
                'updated_at:datetime',
            ],
        ]) ?>
    </div>
</div>