core/backend/controllers/DropshipController.php
<?php

namespace backend\controllers;

use common\models\user\search\UserSearch;
use common\models\user\User;
use Yii;
use common\models\dropship\Dropship;
use common\models\dropship\search\DropshipSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DropshipController implements the CRUD actions for Dropship model.
 */
class DropshipController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Dropship models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->redirect('/users/dropship');

    }

    /**
     * Displays a single Dropship model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Dropship model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Dropship();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Dropship model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Dropship model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Dropship model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Dropship the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Dropship::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findUser($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

core/backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use common\helpers\myHellpers;

use Yii;
use common\models\courses\CoursesOrder;
use common\models\user\User;
use common\models\user\search\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionTest()
    {
        return $this->render('test');
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex($params='')
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->setUser()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }




    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->setUser()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionGetOrders(){
        $model = CoursesOrder::find()->all();
        
        return $this->render('c_orders', [
            'model' => $model,
        ]);
    }


    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id){
        (Yii::$app->user->can('SUPERADMIN'))  ? $this->findModel($id)->delete() : $this->findModel($id)->trash();
        return $this->redirect(['index']);
    }





    public function actionDropship(){
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchDrop(Yii::$app->request->queryParams);

        return $this->render('drop-index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }




}

core/frontend/controllers/DropshipController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\forms\PartnerCourseForm;

class DropshipController extends \yii\web\Controller
{
    //public $layout = 'dropship';
    public function actionIndex()
    {
        $model = new PartnerCourseForm();
        if($model->load(Yii::$app->request->post()) && $model->addPartner()){
            return $this->redirect('/opt/thanks');
        }
        return $this->render('index',[
            'model'=>$model,
        ]);
    }

}

core/backend/views/dropship/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\dropship\Dropship */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dropship-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($model, 'id')->textInput() ?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

core/backend/views/dropship/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\dropship\search\DropshipSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dropship-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

core/backend/views/dropship/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\dropship\Dropship */

$this->title = Yii::t('app', 'Create Dropship');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Dropships'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dropship-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]) ?>

</div>

core/backend/views/dropship/drop-index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel common\models\user\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-header with-border">
        <?= Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <? try {
          echo  GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    [
                        'attribute' => 'status_drop',
                        'value' => function ($data) {

                            return \common\helpers\myHellpers::getStatusLabel(
                                $data->status_drop,
                                \common\models\MainModel::STATUS_MODERATE,
                                \common\models\MainModel::STATUS_BADGE_USER);
                        },
                        'format' => 'html',
                        'label' => 'Статус',
                    ],
                    'name',
                    'email:email',
                    'phone',
                    [
                        'attribute' => 'created_at',

                        'format' => 'datetime',
                        'label' => 'Время заявки'
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{leadView} {leadUpdate} {leadDelete}',
                        'buttons' => [
                            'leadView' => function ($url, $model) {
                                $url = Url::to(['users/view', 'id' => $model->id]);
                                return Html::a('<span class="fa fa-eye"></span>', $url, ['title' => 'view']);
                            },
                            'leadUpdate' => function ($url, $model) {
                                $url = Url::to(['users/update', 'id' => $model->id]);
                                return Html::a('<span class="fa fa-pencil"></span>', $url, ['title' => 'update']);
                            },
                            'leadDelete' => function ($url, $model) {
                                $url = Url::to(['users/delete', 'id' => $model->id]);
                                return Html::a('<span class="fa fa-trash"></span>', $url, [
                                    'title' => 'delete',
                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                                    'data-method' => 'post',
                                ]);
                            },
                        ],
                        'visibleButtons' => [
                            'update' => function ($model) {
                                return '';
                            },
                            'delete' => function ($model) {
                                return '';
                            },
                        ]
                    ],
                ],
                'layout' => "{items}\n{summary}\n{pager}",
            ]);
        } catch (Exception $e) {
        } ?>
    </div>
    <?php Pjax::end(); ?>
</div>

core/backend/views/dropship/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\dropship\search\DropshipSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Dropships');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dropship-index box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-header with-border">
        <?= Html::a(Yii::t('app', 'Create Dropship'), ['create'], ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

core/backend/views/dropship/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\dropship\Dropship */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Dropship',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Dropships'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="dropship-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

core/backend/views/dropship/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\dropship\Dropship */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Dropships'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dropship-view box box-primary">
    <div class="box-header">
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger btn-flat',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
            ],
        ]) ?>
    </div>
</div>